name: "Check PR Title"
on: push

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PR Title Verify
        uses: satvik-s/pr-title-check
        with:
          pattern: '^[A-z]+-\d+(:| -) \w(.){4,}$'
