name: "Check PR Title"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PR Title Verify
        uses: satvik-s/pr-title-check
        with:
          pattern: '^[A-z]+-\d+(:| -) \w(.){4,}$'
