name: Coveragee

on: pull_request

env:
  base_branch: ${{ github.event.pull_request.base.ref }}

jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Cache Node Modules
      #   id: yarn-cache
      #   uses: actions/cache@v3
      #   with:
      #     path: node_modules
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Fetch Base branch
        run: git fetch --no-tags --depth=1 origin ${{ env.base_branch }}

      - name: Switch to Base branch
        run: git checkout -f ${{ env.base_branch }}

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Base Dependencies
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Create Base report
        run: yarn test --ci --json --coverage --testLocationInResults --outputFile=baseReport.json

      - name: Switch to Head branch
        run: git checkout -

      - name: Install Head Dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Create Head report
        run: yarn test --ci --json --coverage --testLocationInResults --outputFile=headReport.json

      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          annotations: none
          base-coverage-file: ./baseReport.json
          coverage-file: ./headReport.json
