name: Coverage

on:
  pull_request:
    branches:
      - main
      - test

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch Main branch
        run: git fetch --no-tags --depth=1000 origin main

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn install
        env:
          CI: true

      - name: Get Coverage
        run: yarn test --changedSince=origin/main --coverage
        env:
          CI: true
