name: Coverage

on:
  pull_request:
    branches:
      - main
      - test

env:
  base_branch: ${{ github.event.pull_request.base.ref }}

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch Main branch
        run: git fetch --no-tags --depth=1 origin ${{ env.base_branch }}

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn install

      - name: Get Coverage
        run: yarn test --changedSince=origin/${{ env.base_branch }} --coverage
